/*
 * AI-assisted (CS3219 AI Usage Policy disclosure):
 * Tool: Claude Code (Sonnet 5), 2026-09-23; revised 2026-09-24.
 * Scope: fixed a compile error (missing java.io.FileReader import), a
 * Maven build failure (CsvToBean has no setType(Class) method in
 * opencsv 5.9; rebuilt via CsvToBeanBuilder.withType(...) instead), and
 * a runtime failure in the containerized service (a relative
 * filesystem path can't resolve inside the runtime image, which only
 * contains the built jar — src/main/resources/csv/... is packaged as a
 * classpath resource, not a file on disk there; switched to loading it
 * via ClassPathResource). No design changes.
 * 2026-09-24: added SupplierTypes seeding alongside Suppliers, per author
 * decision that SupplierTypes.id is a foreign key sharing each Supplier's
 * autogenerated id (@MapsId). Since that id only exists once a Supplier
 * row is persisted, each row is now saved individually (rather than
 * batched via saveAll) so its generated id is available immediately for
 * building the matching SupplierTypes row from the same CSV row's Type
 * column.
 * Revised same day: a supplier can carry multiple types in one CSV cell
 * (e.g. "Food/Coffee"), so the Type column is now split on "/" and one
 * SupplierTypes row is saved per resulting type, per author decision.
 * Renamed same day, SupplierTypes -> SupplierCategories (class, table,
 * repository, id class); the internal "type" field/getter/setter were
 * initially kept as-is, then also renamed to "category" (including
 * Suppliers.type -> Suppliers.category) per author decision — the CSV
 * file and its "Type" header were explicitly left untouched, since
 * @CsvBindByName(column = "Type") binds by the CSV's actual header text,
 * not the Java field name.
 * Reviewed by: Ko-Khan (via pull request).
 */
package foc.supplier.seed;

import com.opencsv.bean.CsvToBean;
import com.opencsv.bean.CsvToBeanBuilder;

import foc.supplier.model.SupplierCategories;
import foc.supplier.model.Suppliers;
import foc.supplier.repository.SupplierCategoriesRepository;
import foc.supplier.repository.SuppliersRepository;

import org.springframework.boot.CommandLineRunner;
import org.springframework.core.io.ClassPathResource;
import org.springframework.stereotype.Component;

import java.io.InputStreamReader;
import java.nio.charset.StandardCharsets;

@Component
public class SuppliersSeeder implements CommandLineRunner {
    private final SuppliersRepository suppliersRepository;
    private final SupplierCategoriesRepository supplierCategoriesRepository;

    public SuppliersSeeder(SuppliersRepository suppliersRepository, SupplierCategoriesRepository supplierCategoriesRepository) {
        this.suppliersRepository = suppliersRepository;
        this.supplierCategoriesRepository = supplierCategoriesRepository;
    }

    @Override
    public void run(String... args) throws Exception {
        if (suppliersRepository.count() == 0) {
            ClassPathResource csvResource = new ClassPathResource("csv/supplier-seed-data.csv");

            try (InputStreamReader reader = new InputStreamReader(csvResource.getInputStream(), StandardCharsets.UTF_8)) {
                CsvToBean<Suppliers> csvToBean = new CsvToBeanBuilder<Suppliers>(reader)
                        .withType(Suppliers.class)
                        .withIgnoreLeadingWhiteSpace(true)
                        .build();

                for (Suppliers supplier : csvToBean) {
                    Suppliers savedSupplier = suppliersRepository.save(supplier);

                    for (String category : savedSupplier.getCategory().split("/")) {
                        SupplierCategories supplierCategory = new SupplierCategories();
                        supplierCategory.setSupplier(savedSupplier);
                        supplierCategory.setCategory(category.trim());
                        supplierCategoriesRepository.save(supplierCategory);
                    }
                }
            } catch (Exception e) {
                throw new IllegalStateException("Failed to seed suppliers", e);
            }

        }
    }
}