-- AI-assisted (CS3219 AI Usage Policy disclosure):
-- Tool: Claude Code (Opus 5.5), 2026-10-09.
-- Scope: the credit-service schema transcribed from docs/credit-service.md
-- ("Database" section: the ER diagram, the table purposes and "How their
-- consistency is maintained"). Tables, columns, keys and CHECK constraints
-- are the team's design; the tool chose only SQL details the doc leaves
-- open (varchar lengths, NOT NULL on columns the doc doesn't mark
-- nullable, constraint and index names) following user-service's V1.
-- 2026-10-10 (PR #166 review): the slice amount CHECK and the slice
-- request_ref index added.
-- Author review: Ryan Ang, pending pull request review.

-- A user's credit balances, one row per user. The primary key makes
-- get-or-create happen once per user (D6). Total is available + reserved,
-- never stored.
create table credit_account (
    user_id varchar(255) not null,
    available integer not null,
    reserved integer not null,
    created_at timestamp(6) with time zone not null,
    primary key (user_id),
    constraint credit_account_available_non_negative check (available >= 0),
    constraint credit_account_reserved_non_negative check (reserved >= 0)
);

-- The reservation for one request. The primary key on request_ref is the
-- duplicate check (D3); status records the outcome. A RELEASED row may
-- carry amount 0 (the tombstone for a cancel that arrives first; the
-- release path get-or-creates the requester's account before writing it,
-- D6).
create table credit_reservation (
    request_ref varchar(255) not null,
    requester_id varchar(255) not null,
    courier_id varchar(255),
    amount integer not null,
    status varchar(255) not null,
    created_at timestamp(6) with time zone not null,
    settled_at timestamp(6) with time zone,
    primary key (request_ref),
    constraint credit_reservation_requester_fk foreign key (requester_id) references credit_account (user_id),
    constraint credit_reservation_courier_fk foreign key (courier_id) references credit_account (user_id),
    constraint credit_reservation_status_check
        check (status in ('HELD', 'REJECTED', 'TRANSFERRED', 'RELEASED')),
    constraint credit_reservation_held_has_amount check (status <> 'HELD' or amount > 0),
    constraint credit_reservation_transfer_has_courier check (status <> 'TRANSFERRED' or courier_id is not null)
);

-- Which lots a reservation's credits came from, so a release returns them
-- with their original expiry (D4).
create table credit_reservation_slice (
    id bigint generated by default as identity,
    request_ref varchar(255) not null,
    amount integer not null,
    earned_at timestamp(6) with time zone not null,
    expires_at timestamp(6) with time zone,
    primary key (id),
    constraint credit_reservation_slice_reservation_fk
        foreign key (request_ref) references credit_reservation (request_ref),
    constraint credit_reservation_slice_amount_positive check (amount > 0)
);

-- a reservation's slices, read back on release
create index idx_credit_reservation_slice_request_ref on credit_reservation_slice (request_ref);

-- A user's available credits split by expiry date (F6.1). A null
-- expires_at never expires (the sign-up credits). Deleted when spent to 0.
create table credit_lot (
    id bigint generated by default as identity,
    owner_id varchar(255) not null,
    remaining integer not null,
    earned_at timestamp(6) with time zone not null,
    expires_at timestamp(6) with time zone,
    primary key (id),
    constraint credit_lot_owner_fk foreign key (owner_id) references credit_account (user_id),
    constraint credit_lot_remaining_positive check (remaining > 0)
);

-- lots by owner in expiry order (spending), and lots past their expiry
-- (the expiry run)
create index idx_credit_lot_owner_expires on credit_lot (owner_id, expires_at);
create index idx_credit_lot_expires on credit_lot (expires_at);

-- Every credit operation, append-only (F4.1.1): one row per affected
-- account per operation. amount is always positive; type says which way
-- it moved.
create table credit_history (
    id bigint generated by default as identity,
    user_id varchar(255) not null,
    type varchar(255) not null,
    amount integer not null,
    request_ref varchar(255),
    occurred_at timestamp(6) with time zone not null,
    primary key (id),
    constraint credit_history_user_fk foreign key (user_id) references credit_account (user_id),
    constraint credit_history_type_check check (type in (
        'PROVISION', 'RESERVE', 'RELEASE', 'TRANSFER_OUT', 'TRANSFER_IN', 'EXPIRY', 'REDISTRIBUTION')),
    constraint credit_history_amount_positive check (amount > 0)
);

-- the history view: by user, filtered by date range (F4.1.2, F4.1.3)
create index idx_credit_history_user_occurred on credit_history (user_id, occurred_at);

-- Expired credits awaiting redistribution: a single row (F6.1).
create table common_pool (
    id smallint not null,
    balance integer not null,
    primary key (id),
    constraint common_pool_single_row check (id = 1),
    constraint common_pool_balance_non_negative check (balance >= 0)
);

insert into common_pool (id, balance) values (1, 0);

-- Months already redistributed; the primary key lets one run per month
-- commit (F6.1.1).
create table redistribution_run (
    period char(7) not null,
    distributed integer not null,
    remainder integer not null,
    ran_at timestamp(6) with time zone not null,
    primary key (period)
);

-- Replies waiting to be published, written in the same transaction as the
-- balance change (D10).
create table outbox_event (
    event_id uuid not null,
    event_type varchar(255) not null,
    payload text not null,
    created_at timestamp(6) with time zone not null,
    sent_at timestamp(6) with time zone,
    primary key (event_id)
);
