-- AI-assisted (CS3219 AI Usage Policy disclosure):
-- Tool: Claude Code (Opus 5.5), 2026-09-29, issue #147.
-- Scope: the schema Hibernate's ddl-auto generated before Flyway took over
-- (team decision), dumped from the entities and copied as-is, constraint
-- names included. A fresh database starts here; an existing one (built by
-- ddl-auto) is baselined at version 1 instead (spring.flyway.
-- baseline-on-migrate), so this script never runs against it.
-- Author review: Ryan to review via the PR.

create table users (
    failed_login_attempts integer not null,
    created_at timestamp(6) with time zone not null,
    deleted_at timestamp(6) with time zone,
    id bigint generated by default as identity,
    locked_until timestamp(6) with time zone,
    version bigint default 0 not null,
    email varchar(255) not null,
    password_hash varchar(255) not null,
    role varchar(255) not null check ((role in ('USER','ADMIN','OWNER'))),
    username varchar(255) not null,
    primary key (id),
    constraint idx_users_email unique (email),
    constraint idx_users_username unique (username)
);

create table account_tokens (
    expires_at timestamp(6) with time zone not null,
    id bigint generated by default as identity,
    user_id bigint not null,
    kind varchar(255) not null check ((kind in ('PASSWORD_RESET','RECOVERY'))),
    token_hash varchar(255) not null,
    primary key (id)
);

create table otps (
    attempts integer not null,
    expires_at timestamp(6) with time zone not null,
    id bigint generated by default as identity,
    user_id bigint not null,
    code_hash varchar(255) not null,
    purpose varchar(255) not null check ((purpose in ('SIGNUP','EMAIL_CHANGE'))),
    primary key (id)
);

create table token_denylist (
    expires_at timestamp(6) with time zone not null,
    jti varchar(255) not null,
    primary key (jti)
);

alter table account_tokens
    add constraint FK19h8y4psfcpn5ct8b9mm2o2na
    foreign key (user_id)
    references users;

alter table otps
    add constraint FKseso6nlp9f5fbuilrngn3pbyi
    foreign key (user_id)
    references users;
