-- AI-assisted (CS3219 AI Usage Policy disclosure):
-- Tool: Claude Code (Opus 5), 2026-09-30, issue #88 (PR #150), written
-- when main's Flyway switch (issue #147) was merged into this branch:
-- Hibernate no longer creates tables, so #88's schema change needs a
-- migration of its own.
-- Scope: the generic otps table is dropped — #88 replaced it with a
-- pending table per operation (design decision by Leong Wei Zhi via
-- options Q&A; #92 gets pending_email_changes) — and pending_signups
-- takes its place: a sign-up parked with its hashed code until
-- POST /auth/signup/verify inserts the users row. Column types and the
-- index name match what the PendingSignup entity declares, so a database
-- built by the old ddl-auto matches one built from here.
-- Author review: Leong Wei Zhi to review via the PR.

-- always empty in practice: nothing ever wrote to it (OTP issuance
-- landed with #88, which removed the table), so no data moves
drop table if exists otps;

create table pending_signups (
    attempts integer not null,
    expires_at timestamp(6) with time zone not null,
    id bigint generated by default as identity,
    last_sent_at timestamp(6) with time zone not null,
    code_hash varchar(255) not null,
    email varchar(255) not null,
    password_hash varchar(255) not null,
    username varchar(255) not null,
    primary key (id)
);

-- one live sign-up per email: a repeat is a resend of that row, and only
-- a repeat of its own details may resend it (PR #150 review). Usernames
-- may repeat here — users' own index decides who keeps one
create unique index idx_pending_signups_email on pending_signups (email);
