-- AI-assisted (CS3219 AI Usage Policy disclosure):
-- Tool: Claude Code (Fable 5), 2026-09-30, issue #92.
-- Scope: the pending_email_changes table V3 promised — one pending
-- table per operation (design decision by Leong Wei Zhi via options
-- Q&A on PR #150): an email change requested at PATCH /users/me is
-- parked here with the hashed code mailed to the NEW address, until
-- POST /users/me/email/verify moves it onto the users row. Column
-- types and the index name match the PendingEmailChange entity.
-- Author review: Leong Wei Zhi to review via the PR.

create table pending_email_changes (
    attempts integer not null,
    expires_at timestamp(6) with time zone not null,
    id bigint generated by default as identity,
    last_sent_at timestamp(6) with time zone not null,
    user_id bigint not null,
    code_hash varchar(255) not null,
    new_email varchar(255) not null,
    primary key (id),
    constraint fk_pending_email_changes_user
        foreign key (user_id) references users
);

-- one pending email change per account: a repeat PATCH renews the row
-- (same address) or replaces it (different address — the caller's
-- identity is proven by their login token, unlike a pending sign-up's).
-- new_email is deliberately NOT unique across users: two accounts may
-- pend the same address, verify re-checks against users and its unique
-- email index decides who keeps it (pending_signups' username rule)
create unique index idx_pending_email_changes_user on pending_email_changes (user_id);
