-- AI-assisted (CS3219 AI Usage Policy disclosure):
-- Tool: Claude Code (Fable 5), 2026-09-30, issue #92.
-- Scope: the gate codes for account updates (F2.1.1): POST /users/me/otp
-- parks a hashed code here, mailed to the account's CURRENT email; the
-- mutating request (PATCH /users/me, POST /users/me/password) presents
-- the code and consumes the row. Single-use, one per operation. Column
-- types and the index name match the AccountUpdateOtp entity.
-- Author review: Leong Wei Zhi to review via the PR.

create table account_update_otps (
    attempts integer not null,
    expires_at timestamp(6) with time zone not null,
    id bigint generated by default as identity,
    last_sent_at timestamp(6) with time zone not null,
    user_id bigint not null,
    code_hash varchar(255) not null,
    primary key (id),
    constraint fk_account_update_otps_user
        foreign key (user_id) references users
);

-- one live gate code per account: a repeat request is a resend of that
-- row (the caller's login token proves it's theirs to renew)
create unique index idx_account_update_otps_user on account_update_otps (user_id);
