/*
AI Assistance Disclosure:
Tool: Claude (Sonnet 5), date: 2026-09-22
Scope: Converted user schema into code
Author review: Ryan validated that it matches schema design.
2026-09-23 (Claude Code, Opus 5.5): dropped unique = true from email/username
columns; the named unique indexes already enforce it (PR #126 review).
2026-09-23 (Claude Code, Fable 5), issue #86: role converted from String to
the Role enum (stored as text); representation chosen by Leong Wei Zhi via
options Q&A. The design doc's CHECK constraint (users_role_check) is
generated by Hibernate from the STRING enum mapping — an explicit @Check
was removed as it duplicated the constraint (verified against user-db).
2026-09-27 (Claude Code, Fable 5), issue #93: softDelete added as the shared
soft-delete entry point (entity method chosen by Leong Wei Zhi via options
Q&A); admin removal (#96) switches to it when both are merged.
2026-09-27 (Claude Code, Opus 5.5), PR #135 review: @Version column added
for optimistic locking (team decision), so a role change racing a delete
can't write deleted_at back to null.
2026-09-29 (Claude Code, Opus 5.5), issue #147: Flyway now owns the schema
(team decision; ddl-auto none), so these annotations no longer create
anything. The username index annotation is gone: V2 replaced that
constraint with a unique index on lower(username), which JPA can't express.
*/

package foc.user.entity;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Index;
import jakarta.persistence.Table;
import jakarta.persistence.Version;
import java.time.Instant;

import org.hibernate.annotations.ColumnDefault;


@Entity
@Table(
    name = "users",
    indexes = {
        @Index(name = "idx_users_email", columnList = "email", unique = true)
        // username: unique ignoring case via idx_users_username_lower (Flyway V2)
    }
)
public class User {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @Column(nullable = false)
    private String email;

    @Column(nullable = false)
    private String username;

    @Column(name = "password_hash", nullable = false)
    private String passwordHash;

    @Enumerated(EnumType.STRING)
    @Column(nullable = false)
    private Role role;

    @Column(name = "failed_login_attempts", nullable = false)
    private int failedLoginAttempts = 0;

    @Column(name = "locked_until")
    private Instant lockedUntil;

    @Column(name = "created_at", nullable = false, updatable = false)
    private Instant createdAt = Instant.now();

    /**
     * Soft-delete timestamp.
     * null = active; non-null = account deleted (purged on day 31).
     */
    @Column(name = "deleted_at")
    private Instant deletedAt;

    // optimistic lock: a save made from a stale copy fails instead of
    // overwriting a newer one (e.g. a role change undoing a delete). The
    // default fills existing rows when ddl-auto adds the column.
    @Version
    @ColumnDefault("0")
    @Column(nullable = false)
    private long version;

    public User() {
    }

    public User(String email, String username, String passwordHash, Role role) {
        this.email = email;
        this.username = username;
        this.passwordHash = passwordHash;
        this.role = role;
        this.failedLoginAttempts = 0;
        this.createdAt = Instant.now();
    }

    // getters and setters

    public Long getId() {
        return id;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getPasswordHash() {
        return passwordHash;
    }

    public void setPasswordHash(String passwordHash) {
        this.passwordHash = passwordHash;
    }

    public Role getRole() {
        return role;
    }

    public void setRole(Role role) {
        this.role = role;
    }

    public int getFailedLoginAttempts() {
        return failedLoginAttempts;
    }

    public void setFailedLoginAttempts(int failedLoginAttempts) {
        this.failedLoginAttempts = failedLoginAttempts;
    }

    public Instant getLockedUntil() {
        return lockedUntil;
    }

    public void setLockedUntil(Instant lockedUntil) {
        this.lockedUntil = lockedUntil;
    }

    public Instant getCreatedAt() {
        return createdAt;
    }

    public Instant getDeletedAt() {
        return deletedAt;
    }

    public void setDeletedAt(Instant deletedAt) {
        this.deletedAt = deletedAt;
    }

    public boolean isActive() {
        return this.deletedAt == null;
    }

    /**
     * Marks the account soft-deleted. Shared entry point for
     * self-deletion and admin removal (#96): the row stays put, so the
     * email and username remain reserved until the day-31 purge
     * ({@code AccountPurgeScheduler}); recovery (#94) clears the stamp.
     */
    public void softDelete(Instant at) {
        this.deletedAt = at;
    }
}