/*
 * AI-assisted (CS3219 AI Usage Policy disclosure):
 * Tool: Claude Code (Sonnet 5), 2026-09-24.
 * Scope: changed id from a plain @Id field to a @OneToOne @MapsId
 * association back to Suppliers, per author decision (SupplierTypes.id
 * is a foreign key sharing Suppliers' autogenerated primary key, not an
 * independently generated value). CsvBindByName removed from id since it
 * is no longer populated from the CSV directly (SuppliersSeeder derives
 * it from the saved Suppliers row instead).
 * Revised same day: a supplier can have multiple types (CSV Type column
 * e.g. "Food/Coffee"), so one supplier now maps to many SupplierTypes
 * rows; the association changed from @OneToOne to @ManyToOne, and the
 * primary key is now the composite (id, type) via @IdClass(SupplierTypeId),
 * with id still derived from the associated Suppliers row via
 * @MapsId("id") and type promoted to part of the key.
 * Reviewed by: Ko-Khan (via pull request).
 */
package foc.supplier.model;

import jakarta.persistence.*;

@Entity
@Table(name = "SupplierTypes")
@IdClass(SupplierTypeId.class)
public class SupplierTypes {

    @Id
    private Long id;

    @Id
    private String type;

    @ManyToOne
    @MapsId("id")
    @JoinColumn(name = "id")
    private Suppliers supplier;

    // Getters and Setters

    public Long getId() {
        return id;
    }

    public Suppliers getSupplier() {
        return supplier;
    }

    public void setSupplier(Suppliers supplier) {
        this.supplier = supplier;
    }

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

}
