/*
 * AI-assisted (CS3219 AI Usage Policy disclosure):
 * Tool: Claude Code (Sonnet 5), 2026-09-24.
 * Scope: changed id from a plain @Id field to a @OneToOne @MapsId
 * association back to Suppliers, per author decision (SupplierTypes.id
 * is a foreign key sharing Suppliers' autogenerated primary key, not an
 * independently generated value). CsvBindByName removed from id since it
 * is no longer populated from the CSV directly (SuppliersSeeder derives
 * it from the saved Suppliers row instead).
 * Revised same day: a supplier can have multiple types (CSV Type column
 * e.g. "Food/Coffee"), so one supplier now maps to many SupplierTypes
 * rows; the association changed from @OneToOne to @ManyToOne, and the
 * primary key is now the composite (id, type) via @IdClass(SupplierTypeId),
 * with id still derived from the associated Suppliers row via
 * @MapsId("id") and type promoted to part of the key.
 * Renamed same day, SupplierTypes -> SupplierCategories (class, table,
 * repository, id class); the internal "type" field/getter/setter were
 * initially kept as-is, then also renamed to "category"
 * (getType/setType -> getCategory/setCategory) per author decision for
 * full consistency. @IdClass field names must match the entity's @Id
 * field names exactly, so SupplierCategoryId's field was renamed to
 * match.
 * 2026-10-05 (issue #160, Claude Code (Sonnet 5)): added the static
 * normalizeCategory helper (trim, capitalise first letter, lowercase the
 * rest) used when storing category names.
 * Reviewed by: Ko-Khan (via pull request).
 */
package foc.supplier.model;

import jakarta.persistence.*;
import java.util.Locale;

@Entity
@Table(name = "SupplierCategories")
@IdClass(SupplierCategoryId.class)
public class SupplierCategories {

    // Standard form for every stored category name: trimmed, first letter
    // capitalised, the rest lowercased, so "Food", "food" and "fOOD" all
    // store as "Food". Returns null for blank input so callers can skip it.
    public static String normalizeCategory(String raw) {
        if (raw == null) {
            return null;
        }
        String trimmed = raw.trim();
        if (trimmed.isEmpty()) {
            return null;
        }
        String lower = trimmed.toLowerCase(Locale.ROOT);
        return Character.toUpperCase(lower.charAt(0)) + lower.substring(1);
    }

    @Id
    private Long id;

    @Id
    private String category;

    @ManyToOne
    @MapsId("id")
    @JoinColumn(name = "id")
    private Suppliers supplier;

    // Getters and Setters

    public Long getId() {
        return id;
    }

    public Suppliers getSupplier() {
        return supplier;
    }

    public void setSupplier(Suppliers supplier) {
        this.supplier = supplier;
    }

    public String getCategory() {
        return category;
    }

    public void setCategory(String category) {
        this.category = category;
    }

}
